var uwmData={av:'//www.dealervideos.com/av.aspx?ctx=',availability:'//www.dealervideos.com/integration.svc/availability?ctx=',ctx:'',cobalt:!!window.Cobalt,oldStyleCobalt:!!window.__RESULTS_VEHICLE_DATA,defaultHeight:window.uwmHeight||288,defaultWidth:window.uwmWidth||384};
function uwmInitVideoScripts(){jQuery.extend(uwmData,uwmParseQuery(jQuery('#uwscript').attr('src').split(/[?#]/)[1]||''));if('DDC'==uwmData.shost)if(window.views&&window.views.length)if(0<window.views[0].extra.indexOf('_NEW')||-1<window.views[0].extra.indexOf('NEW_'))uwmData.ctx=uwmData.new_ctx;else{if(0<window.views[0].extra.indexOf('_USED')||-1<window.views[0].extra.indexOf('USED_'))uwmData.ctx=uwmData.used_ctx}else 0<window.location.pathname.toLowerCase().indexOf('used')?uwmData.ctx=uwmData.used_ctx:
uwmData.ctx=uwmData.new_ctx;else uwmData.cobalt||(!uwmData.ctx&&uwmData.used_ctx&&uwmData.new_ctx&&(document.location.pathname.match(/\bnew\b/i)?uwmData.ctx=uwmData.new_ctx:document.location.pathname.match(/\bused\b/i)&&(uwmData.ctx=uwmData.used_ctx)),_uwmUiCheck());uwmStartVinCheck()}function uwmStartVinCheck(){uwmCheckAvailability(uwmDefaultGetVinArray())}
function uwmGetColbaltCtx(d){for(var a='[itemprop="itemCondition"];[data-vehicle-category];span#detailsTitle;span.category;span.vCateogry;header p.h1 span.highlight;span.result_item_title_category'.split(';'),c='';!c&&a.length;)c=d.find(a.pop()).text();c=c.toLowerCase();return-1<c.indexOf('new')?uwmData.new_ctx:-1<c.indexOf('certified')||-1<c.indexOf('used')||c.match(/pre\W*owned/)||-1<c.indexOf('pre-loved')?uwmData.used_ctx:''}
function uwmParseQuery(d){var a={};if(!d||!d.length)return a;d=d.split(/[;&#]/);for(var c=0;c<d.length;c++){var b=d[c].split('=');if(b&&2==b.length){var e=unescape(b[0]),b=unescape(b[1]),b=b.replace(/\+/g,' ');a[e]=b.trim()}}return a}var _uwmUiRequested=!1,_uwmCssRequested=!1;
function _uwmUiCheck(){window.jQuery&&(_uwmUiRequested||jQuery.ui&&jQuery.ui.dialog||(_uwmUiRequested=!0,jQuery.ajax({url:'//www.dealervideos.com/scripts/jquery-ui-dialog.js',dataType:'script',cache:!0})),!_uwmCssRequested&&1>jQuery('style:contains(".ui-dialog")').length&&(_uwmCssRequested=!0,jQuery('<link rel="stylesheet" type="text/css" href="//www.dealervideos.com/css/uwm.dialog.css" />').appendTo('head')))}
function uwmLoadScript(d,a){var c=document.getElementsByTagName('head')[0],b=document.createElement('script');'undefined'!==typeof a&&(b.onload=a);b.type='text/javascript';b.src=d;c.appendChild(b)}var uwmjQueryScriptOutputted=!1;
function uwmInitVideoService(){if('undefined'==typeof jQuery)uwmjQueryScriptOutputted||(uwmjQueryScriptOutputted=!0,uwmLoadScript('//www.dealervideos.com/scripts/jquery-1.5.2.min.js',function(){jQuery.noConflict();_uwmUiCheck()})),setTimeout(uwmInitVideoService,75);else{var d=jQuery().jquery.split('.');1<parseInt(d[0],10)||9<parseInt(d[1],10)?uwmLoadScript('//code.jquery.com/jquery-migrate-1.2.1.min.js',uwmInitIntegration):uwmInitIntegration()}}
function uwmInitIntegration(){jQuery(document).ready(function(){uwmInitVideoScripts()})}function uwmCheckAvailability(d){if(d.length){for(var a={},c={},c=0;c<d.length;++c)d[c].ctx&&(a[d[c].ctx]?a[d[c].ctx].push(d[c].vin):a[d[c].ctx]=[d[c].vin]);for(var b in a)(c=jQuery.getJSON(uwmData.availability+b+'&callback=?',{vin:a[b].toString()},uwmCheckAvailabilityCompleted))&&c.error&&c.error(function(){jQuery('#uwm_cobalt,#uwm_'+a[b].join(',#uwm_')).hide()})}}
function uwmCheckAvailabilityCompleted(d){if(!(d instanceof Array))return!1;for(var a=0;a<d.length;a++){var c=d[a],b=jQuery('#uwm_'+c.vin);if(uwmData.cobalt&&(b=jQuery('#uwm_cobalt'),c.available&&!b.length))if(uwmData.cobaltListings&&uwmData.cobaltListings[c.vin])uwmData.oldStyleCobalt?(b=jQuery(document.createElement('a')).addClass('spriteContainer sprite-icon_video').attr({title:'popup',style:'do-not-change:me'}).text('Video'),uwmData.cobaltListings[c.vin].find('.media_information').removeClass('single_media_information').append(jQuery(document.createElement('li')).append(b))):
(b=jQuery('<li class="icon-camera"><i class="fa fa-video-camera fa-lg" title="Video Available"></i>&nbsp;</li>'),uwmData.cobaltListings[c.vin].find('figure ul').append(b));else if(window.ContextManager.getVin()){var e=jQuery('ul.navigationLinks');e.length?(b=jQuery('ul.navigationLinks>li').eq(0).clone(!1),b.attr('title','popup').css({cursor:'pointer'}).find('a').attr('href','#').text('Walkaround Video'),e.append(b)):(b=jQuery('<li id="uwm_cobalt" style="cursor: pointer" title="popup"><a href="#">Walkaround Video</a></li>'),
jQuery('div.photo-filter>ul').append(b))}b.attr('width')||b.attr('width',384);b.attr('height')||b.attr('height',288);c.available?'undefined'!=typeof uwmVideoAvailableHandler?uwmVideoAvailableHandler(c,b):uwmDefaultVideoAvailableHandler(c,b):'undefined'!=typeof uwmVideoUnavailableHandler?uwmVideoUnavailableHandler(c,b):uwmDefaultVideoUnavailableHandler(c,b)}}function uwmDefaultVideoUnavailableHandler(d,a){a.hide()}function uwmVideoUnavailableHandler(d,a){a.hide()}
function uwmDefaultVideoAvailableHandler(d,a){uwmEmbedVideo(d,a)}
function uwmVideoAvailableHandler(d,a){if(d.available){switch(a.attr('title')){case 'embed':uwmEmbedVideo(d,a);break;case 'popup':''==a.attr('style')||void 0==a.attr('style')?(a.css({width:'150',height:'54',cursor:'pointer'}),a.append('<img src="//www.dealervideos.com/css/fdIcons/default.png" alt="Click for Video"></img>')):a.append('<span></span>');uwmPopUp(d,a);break;case 'dialog':''==a.attr('style')||void 0==a.attr('style')?(a.css({width:'150',height:'54',cursor:'pointer'}),a.append('<img src="//www.dealervideos.com/css/fdIcons/default.png" alt="Click for Video"></img>')):
a.append('<span></span>');uwmDialogVideo(d,a);break;case 'notification':''==a.attr('style')||void 0==a.attr('style')?a.append('Video Available'):a.append('<span></span>')}a.removeAttr('title')}else a.hide()}function uwmPopUp(d,a){var c=a.attr('height')||uwmData.defaultHeight,b=a.attr('width')||uwmData.defaultWidth;d.available?a.click(function(){window.open(uwmData.av+d.ctx+'&vid='+d.contentId,'uwm_video','width='+b+',height='+c+',resizable=no,scrollbars=no,status=no');return!1}):a.hide()}
function uwmEmbedVideo(d,a){function c(d,b){var c='',g=a.css(d);!b||'auto'!=g&&'0px'!==g||(c+=';'+d+':'+b,'%'!==b[b.length-1]&&(c+='px'));return c}if(d.available){var b=c('height',a.attr('height'))+c('width',a.attr('width'));b&&a.attr('style',(a.attr('style')||'')+b);a.append(uwmUniversalDelivery(d,a))}else a.hide()}function uwmYouTubeObject(d,a){return uwmUniversalDelivery(d,a)}
function uwmUniversalDelivery(d,a){var c=a.attr('height')||uwmData.defaultHeight,b=a.attr('width')||uwmData.defaultWidth;return"<iframe src='"+uwmData.av+d.ctx+'&vid='+d.contentId+"' height='"+c+"' width='"+b+"' frameborder='0' scrolling='no' allowfullscreen='allowfullscreen' seamless='seamless'></iframe>"}
function uwmDialogVideo(d,a){d.available?a.click(function(c){c.preventDefault();var b=parseInt(a.attr('width'),10)||uwmData.defaultWidth,e=parseInt(a.attr('height'),10)||uwmData.defaultHeight,f=jQuery("<div id='uwmDialog' title='Video Player'><div id='uwmSwfObject'></div></div>").appendTo('body');f.dialog({autoOpen:!1,draggable:!0,width:b+40,height:e+65,minHeight:e+65,modal:!0,dialogClass:'uwmDialogClass',resizable:!1}).bind('dialogopen',function(){uwmEmbedVideo(d,f.children('#uwmSwfObject').empty().attr({height:e,
width:b}).height(e).width(b))}).bind('dialogbeforeclose',function(){f.empty().remove()}).dialog('open');return!1}):a.hide()}
function uwmDefaultGetVinArray(){var d=[];if(window.Cobalt){var a={},c=[],b=window.ContextManager.getVin(),e='';if(b)d.push({vin:b,ctx:uwmGetColbaltCtx(jQuery('body'))});else if(uwmData.cobaltListings={},uwmData.oldStyleCobalt){var a=window.__RESULTS_VEHICLE_DATA.Results,f;for(f in a)a.hasOwnProperty(f)&&(c=jQuery('#result_item_'+f),b=a[f].vin||c.find('li:contains(VIN:)>span').text(),e=uwmGetColbaltCtx(c),b&&e&&(d.push({vin:b,ctx:e}),uwmData.cobaltListings[b]=c))}else a=jQuery('article[itemtype="http://schema.org/IndividualProduct"]'),
a.each(function(a,b){b=jQuery(b);var c=b.find('.Vin').next().text()||b.find('.imageContainer').data('vin')||'',e=uwmGetColbaltCtx(b);c&&e&&(d.push({vin:c,ctx:e}),uwmData.cobaltListings[c]=b)})}else jQuery("[id^='uwm_']").each(function(){d[d.length]={vin:jQuery(this).attr('id').substring(4),ctx:uwmData.ctx}});return d}uwmInitVideoService();
