(function(){if(window.ggLoader)throw Error("toolbar already loaded");ggLoader={};ggConfig={data:{account_id:101344,generated_at:1488484505,api_url:"https://gubagoo.io/api",environment:"production",server_url:"https://gubagoo.io",comet_url:"https://chat-node-proxy.gubagoo.io",show_in_iframe:!1,toolbar_id:1,toolbar_cdn:"https://gubagoo.io",toolbar_enabled:1,hidden:"0",default_state:"",mobile_state:!1,language:"en",toolbar_small:"",mobile_toolbar_small:"",disable_mobile:!1,always_load_jquery:!1,prevent_jquery_load:!1,
toolbar_hide_copyright:!1,show_privacy:"default"}};ggFramework=window.ggFramework||{};(function(){ggFramework.loadedFiles={};var b=ggFramework.loadedFiles;window.ggUrl=function(a){-1==a.indexOf("//")&&(a=ggConfig.get("toolbar_cdn")+a);return a};ggFramework.serialize=function(a,c){var d=[],b;for(b in a)if(a.hasOwnProperty(b)){var e=c?c+"["+b+"]":b,g=a[b];d.push("object"==typeof g?ggFramework.serialize(g,e):encodeURIComponent(e)+"="+encodeURIComponent(g))}return d.join("&")};ggFramework.sendRequest=
function(a,c,d,b){c=c||{};"jsonp"==b&&(c.jsonp=!0);b&&(c.data_type=b);a=ggUrl(a);(c=c?ggFramework.serialize(c):!1)&&0<c.length&&(a+="?"+c);var e=window.XDomainRequest?new XDomainRequest:new XMLHttpRequest;e.open("GET",a,!0);e.timeout=18E3;e.onerror=function(a){console.log("CORS error",a)};e.onprogress=function(){};e.onload=function(){e.readyState||(e.readyState=4,e.status=200);if(4===e.readyState)if(200<=e.status&&400>e.status)switch(b){case "text":d(e.responseText);break;default:d(JSON.parse(e.responseText))}else throw"Response returned with non-OK status";
};e.send();window.XDomainRequest&&ggFramework.pendindRequests.push(e);return e};ggFramework.pendindRequests=[];ggFramework.executeJs=function(a){eval(a)};ggFramework.getScript=function(a,c,d,f){a=ggUrl(a);if(d)return ggFramework.loadFromCache(a,function(d,f){f&&ggFramework.executeJs(f);ggFramework.executeJs(d);b[a]=!0;c&&c(!1)}),!1;var e=!1,g=document.createElement("script");f&&f.id&&g.setAttribute("id",f.id);g.type="text/javascript";g.onload=g.onreadystatechange=function(){e||this.readyState&&"loaded"!==
this.readyState&&"complete"!==this.readyState||(e=!0,c&&c(g),g.onload=g.onreadystatechange=null)};g.src=a;document.getElementsByTagName("head")[0].appendChild(g)};ggFramework.getCss=function(a,c){if(b[a])return!1;a=ggUrl(a);if(c)return ggFramework.loadFromCache(a,function(c){ggFramework.insertRawCss(c);b[a]=!0}),!1;var d=document.createElement("link");d.setAttribute("rel","stylesheet");d.setAttribute("type","text/css");d.setAttribute("href",a);document.getElementsByTagName("head")[0].appendChild(d);
b[a]=!0};ggFramework.loadFromCache=function(a,c){var b=a.split(".").pop(),f=b+"-"+ggFramework.hash(a),e=ggStorage.getCache(f);if(e)return c(e),!0;"js"==b&&(a="/v2/modules/toolbar/js_proxy/index.php?path="+encodeURIComponent(a));ggFramework.sendRequest(a,{},function(a){var e=a;a.content&&(e=a.content);"css"==b&&(e=e.split("/v2/media/fonts").join(ggConfig.get("toolbar_cdn")+"/v2/media/fonts"),e=e.split("../media/").join(ggConfig.get("toolbar_cdn")+"/v2/media/"));ggStorage.setCache(f,e);c(e,a.plugins)},
"css"==b?"text":"json");return!1};ggFramework.insertRawCss=function(a){var c=document.createElement("style");c.setAttribute("type","text/css");document.getElementsByTagName("head")[0].appendChild(c);c.styleSheet?c.styleSheet.cssText=a:c.innerHTML=a};ggFramework.require=function(a,c,d,f){if(b[a])return c&&c(),!1;b[a]=!0;ggFramework.getScript(a,c,d,f)};ggFramework.hash=function(a){var c=0,b,f,e;if(0==a.length)return c;b=0;for(e=a.length;b<e;b++)f=a.charCodeAt(b),c=(c<<5)-c+f,c|=0;return c}})();window.ggHook=
function(){var b=[];return{register:function(a,c,d){"undefined"==typeof b[a]&&(b[a]=[]);d?b[a].unshift(c):b[a].push(c)},fire:function(a,c){if("undefined"!=typeof b[a])for(var d=0;d<b[a].length&&-1!==b[a][d](c);++d);}}}();ggConfig=window.ggConfig||{data:{}};ggConfig.get=function(b){return"undefined"!=typeof this.data[b]?this.data[b]:!1};ggConfig.set=function(b,a){this.data[b]=a};ggConfig.extend=function(b){for(var a in b)this.data[a]=b[a]};ggFramework.cookie_enabled=null;ggFramework.checkCookie=function(){if(null!==
ggFramework.cookie_enabled)return ggFramework.cookie_enabled;var b=navigator.cookieEnabled?!0:!1;"undefined"!=typeof navigator.cookieEnabled||cookieEnabled||(document.cookie="testcookie",b=-1!=document.cookie.indexOf("testcookie")?!0:!1);return ggFramework.cookie_enabled=b};ggFramework.setCookie=function(b,a,c){c=c||{expires:1800,path:"/",domain:window.location.hostname};c.domain=c.domain.replace("www.","");var d=c.expires;if("number"==typeof d&&d){var f=new Date;f.setTime(f.getTime()+1E3*d);d=c.expires=
f}d&&d.toUTCString&&(c.expires=d.toUTCString());a=encodeURIComponent(a);b=b+"="+a;for(var e in c)b+="; "+e,a=c[e],!0!==a&&(b+="="+a);document.cookie=b};ggFramework.getCookie=function(b){return(b=document.cookie.match(new RegExp("(?:^|; )"+b.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(b[1]):void 0};window.ggStorage=new function(){var b=!1,a=this;"undefined"!==typeof Storage&&(b=!0);try{localStorage.setItem("test",1)}catch(c){b=!1}finally{b&&localStorage.removeItem("test")}b&&
!ggFramework.checkCookie()&&(b=!1);this.enabled=b;this.get=function(a){return b?localStorage.getItem("gg_"+a):!1};this.set=function(a,c){if(!b)return!1;localStorage.setItem("gg_"+a,c)};this.remove=function(a){if(!b)return!1;localStorage.removeItem("gg_"+a)};this.test=function(a){return b?null!==localStorage.getItem("gg_"+a):!1};this.setJSON=function(b,c){a.set(b,JSON.stringify(c))};this.getJSON=function(b){if(b=a.get(b))try{b=JSON.parse(b)}catch(c){b=!1}return b};this.cache_fallback={};this.getCache=
function(a){if(!b)return ggStorage.cache_fallback[a];var c=ggStorage.get(a+"_time");return c&&ggConfig.get("generated_at")<=parseInt(c)?ggStorage.get(a):!1};this.setCache=function(a,c){b||(ggStorage.cache_fallback[a]=c);ggStorage.set(a+"_time",ggConfig.get("generated_at"));ggStorage.set(a,c)}};ggFramework.ie=function(){if(ggFramework.ie_version)return ggFramework.ie_version;var b=/(msie) ([\w.]+)/i.exec(navigator.userAgent)||[],b=1<b.length?parseInt(b[2]):!1;!b&&/Trident\/7\./.test(navigator.userAgent)&&
(b=11);ggFramework.ie_version=b?b:99;return ggFramework.ie_version};ggFramework.isMobile=function(){if("#m"==window.location.hash)return!0;for(var b="iphone,ipod,ipad,series60,symbian,android,windows ce,blackberry,palm,avantgo,docomo,vodafone,j-phone,xv6850,htc,lg;,lge,mot,nintendo,nokia,samsung,sonyericsson,bb10".split(","),a=navigator.userAgent.toLowerCase(),c=0;c<b.length;c++)if(null!=a.match(b[c]))return!0;return!1};window.ggLoader={isMobile:!1,disabled:!1,loadToolbar:function(){var b="toolbar_";
ggLoader.isMobile&&(b="toolbar_m_");10>ggFramework.ie()&&(b="toolbar_ie_");b+=ggConfig.get("account_id")+"_"+ggConfig.get("toolbar_id")+".js";ggFramework.getScript(ggLoader.toolbarUrl(b),!1,ggConfig.get("debug")?!1:!0)},init:function(){ggLoader.isMobile=ggFramework.isMobile();if(!ggConfig.get("toolbar_enabled")||!ggConfig.get("show_in_iframe")&&window!=window.top||8>ggFramework.ie()||ggLoader.isMobile&&ggConfig.get("disable_mobile")||ggTracking.checkHeadless()||"true"==ggStorage.get("toolbar_blocked"))return!1;
this.loadScripts();return!0},loadScripts:function(){"function"==typeof jQuery||ggConfig.get("prevent_jquery_load")||ggFramework.getScript("/v2/modules/toolbar/jquery.js",!1,!0);ggLoader.loadToolbar()},toolbarUrl:function(b){return"/toolbars/toolbar_"+ggConfig.get("account_id")+"/"+b}};window.ggTracking=new function(){var b=this;this.version="0.5";this.is_sent=!1;this.location=this.resolution=this.lang=this.referer=this.platform=this.browser=this.title="";this.scheme="http";this.account_id=!1;this.visitor_uid=
"";this.ip=this.test_mode=this.img=this.is_new_session=!1;this.check_unique=!0;this.track_mode="jsonp";this.append_params={};this.track_key=this.track_response=!1;this.cookie_enabled=!0;this.init=function(a){this.track_key=window.gubagooTrackKey||"mock";this.account_id=a;this.getParams()};this.getParams=function(){"https"==document.location.href.substr(0,5)&&(this.scheme="https");document.title&&(this.title=this.trim(document.title));document.referrer&&(this.referer=document.referrer);0==this.referer.toString().length&&
(this.referer=this.getRequestParam("referer"));window.location&&(this.location=window.location);this.resolution=screen.width+"_"+screen.height;this.lang=(navigator.language||navigator.browserLanguage).substr(0,2);this.parseUserAgent(navigator.userAgent);this.cookie_enabled=ggFramework.checkCookie();this.check_unique&&this.checkUnique()};this.trim=function(a){return a.replace(/^\s+|\s+$/g,"").substr(0,80)};this.getByPattern=function(a,b,d){for(var f in b){var e=b[f];if(0<=e.indexOf("/")){if(null!=
(new RegExp(e,"i")).exec(a)){d=f;break}}else if(0<=a.indexOf(e)){d=f;break}}return d};this.parseUserAgent=function(a){var b="";a=a.toLowerCase();var d=this.getByPattern(a,{ip:"iphone",ipad:"ipad",an5:"android 5",an4:"android 4",an:"android",bb:"blackberry",nk:"nokia",ipod:"ipod",ox:"mac os x",w2:"windows nt 5.0",w3:"windows nt 5.2",xp:"windows nt 5.1",vi:"windows nt 6.0",w7:"windows nt 6.1",w8:"windows nt 6.2",w81:"windows nt 6.3",w10:"windows nt 10.0",chrome_os:"cros",wn:"windows",ub:"ubuntu",lx:"linux",
un:"/(unix|bsd)/",mo:"/(midp|mobile|j2me|symbian)/"},"un"),b=this.getByPattern(a,{ff:"firefox",ie11:"trident/7.0; rv:11.0",ie10:"msie 10",ie9:"msie 9",ie8:"msie 8",edge:"edge",ie:"/(msie)/",ch:"chrome",sf:"safari",op:"opera",bt:"/(bot|crawl|spider|bingbot)/",mo:"/(blackberry|nokia|midp|mobile|j2me|symbian)/"},"un");"bt"==b&&"un"==d&&(d="bt");"mo"==b&&"un"==d&&(d="mo");this.platform=d;this.browser=b;return{platform:d,browser:b}};this.refreshSession=function(){ggFramework.setCookie("__ggtrses",1,{expires:1800,
path:"/",domain:window.location.hostname})};this.checkUnique=function(){var a=ggFramework.getCookie("__ggtruid");if(!this.cookie_enabled)a=!1;else if(!a||0>=a.toString().length||"undefined"==a)a=this.guidGenerator(),ggFramework.setCookie("__ggtruid",a,{expires:63072E3,path:"/",domain:window.location.hostname});this.visitor_uid=a;a=ggFramework.getCookie("__ggtrses");this.is_new_session=!a||0>=a.toString().length?!0:!1;this.refreshSession()};this.onTrackResponse=function(a){a.visitor_guid&&(b.visitor_uid=
a.visitor_guid);b.track_response=a};this.sendRequest=function(){if(!this.track_key)return!1;if("jsonp"==this.track_mode){var a=this.prepareRequest(!0);a.data_type="json";a.callback="ggTracking.onTrackResponse";window.location.hash&&(a.hash=window.location.hash.split("#").join(""));ggConfig.get("toolbar_id")&&(a.toolbar_id=ggConfig.get("toolbar_id"));a.firestamps=ggFramework.getCookie("gg_firestamps_json");window.ggStorage&&(a.tabs={po:ggStorage.get("po_tabs"),bb:ggStorage.get("bb_tab")});ggFramework.sendRequest(this.getRequestUrl(a),
{},ggTracking.onTrackResponse)}else this.img=new Image,a=this.prepareRequest(!0),"pixel_timeout"==this.track_mode&&(a.pixel_timeout="1"),this.img.src=this.getRequestUrl(a);ggTracking.is_sent=!0};this.trackAction=function(a,b,d){if(!this.track_key)return!1;this.refreshSession();this.img=new Image;a=this.prepareRequest(!1,a,b);a=this.getRequestUrl(a);d&&(a=a+"&"+ggFramework.serialize(d));this.img.src=a};this.prepareRequest=function(a,b,d){b={ver:this.version,key:this.track_key,__ggtruid:this.visitor_uid,
ref:this.referer,title:this.title,href:this.location.toString(),res:this.resolution,ta:b||1};if(this.append_params)for(var f in this.append_params)this.append_params.hasOwnProperty(f)&&(b[f]=this.append_params[f]);a&&(b.pl=this.platform,b.br=this.browser,b.lang=this.lang);"undefined"!=typeof d&&d&&(b.tast=d);window.ggLoader&&window.ggLoader.isMobile&&(b.mobile="1");this.is_new_session&&(b.__ggtrns="1",this.is_new_session=!1);this.cookie_enabled||(b.cookie_disabled=!0);this.test_mode&&this.ip&&(b.test=
"1",b.ip=this.ip);b.t=(new Date).getTime();return b};this.getRequestUrl=function(a){return ggConfig.get("server_url")+"/track/"+this.account_id+"/?"+ggFramework.serialize(a)};this.guidGenerator=function(){var a=function(){return(65536*(1+Math.random())|0).toString(16).substring(1)},b=(new Date).getTime()+".";return b+=a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()};this.checkHeadless=function(){if("development"==ggConfig.get("environment"))return!1;if(window._phantom||window.callPhantom)return"phantom";
if(window.__phantomas)return"phantomas";if(window.Buffer)return"nodejs";if(window.emit)return"couchjs";if(window.spawn)return"rhino";if(window.webdriver)return"selenium";if(1024==screen.width){if(0===window.outerWidth&&0===window.outerHeight)return"headless";if(!(navigator.plugins instanceof PluginArray)||0==navigator.plugins.length)return"headless plugin";if(!navigator.onLine||!Function.prototype.bind||Function.prototype.bind.toString().replace(/bind/g,"Error")!=Error.toString()||Function.prototype.toString.toString().replace(/toString/g,
"Error")!=Error.toString())return"headless"}return!1};this.getVisitorGuid=function(){return this.visitor_uid};this.getRequestParam=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(location.search);return null===a?"":decodeURIComponent(a[1].replace(/\+/g," "))}};ggTracking.init(ggConfig.get("account_id"));ggLoader.init()||(ggTracking.track_mode="pixel");ggConfig.get("track_append_params")&&(ggTracking.append_params=ggConfig.get("track_append_params"));
ggTracking.sendRequest()})();
