

























LL_setcookie('LLUID','c3447d37-6c23-48ec-b761-fc626577f1ac');var fbtrack = new Image(1,1);fbtrack.src='https://www.facebook.com/tr?ev=PageView&id=1301000869912871';fbtrack.style.display='none';document.body.appendChild(fbtrack);var fbtrack2 = new Image(1,1);fbtrack2.src='https://www.facebook.com/tr?ev=ViewContent&id=1301000869912871';fbtrack2.style.display='none';document.body.appendChild(fbtrack2);var track = new Image(1,1);track.src='https://cm.lotlinx.com/86000/pixel?lotlinxtraffic=yes&VDP=yes&dealerid=60379&url=' + encodeURIComponent(document.URL) + '';track.style.display='none';document.body.appendChild(track);(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', 'UA-6438777-3', 'auto', 'LLtracker'); if(document.readyState === 'complete' || document.readyState === 'interactive' || document.readyState === 'loaded') {    var URI = window.location.pathname;    document.onclick = function() {        if (typeof ga === 'function'){           ga('LLtracker.send', 'event',  'AllVDPClicks', 'clicks', URI);        }    };} else {   document.addEventListener('DOMContentLoaded', function() {     var URI = window.location.pathname;    document.onclick = function() {        if (typeof ga === 'function'){           ga('LLtracker.send', 'event',  'AllVDPClicks', 'clicks', URI);        }    };  });}

